如果是难题会用*号做对应的标注，普通问题则不会

- maven的idea集成

由于我自己的idea重装过，导致maven在idea中的集成需要再做一次，这里我分别按照我之前做过的笔记，以及通过CSDN里的这篇文章https://blog.csdn.net/Z2424858916/article/details/124357056，解决了这个问题，成功将本地仓库的位置设定好

- idea自动导包问题

maven中即使已经事先加载了对应的依赖，但是在实际的类里却无法使用。手动导入对应的包的地址之后这个问题就解决了

- 启动项目时报错org.yaml.snakeyaml.error.YAMLException: java.nio.charset.MalformedInputExcept

这个问题是由于字符集输入格式错误导致的，在idea中修改字符集即可，具体的解决过程参考这个地址https://blog.csdn.net/JiaMing11_27/article/details/120303291

- 数据库连接地址错误

产生这个问题的原因是课程里使用的数据库是本地数据库，而我们使用的数据库是远程的数据库，因此会报错，显示连接不上对应的数据库，下面是我们原来的数据库的连接地址

```
url: jdbc:mysql://localhost:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
```

我们将其改为如下形式即可，其实就是将对应的localhost改为我们的远程连接的ip地址，同时由于我们的数据库设置了密码，因此我们这里同时要设置对应的密码

```
driver-class-name: com.mysql.cj.jdbc.Driver
url: jdbc:mysql://175.178.114.158:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
username: root
password: itheima
```

为了查询密码顺便还重新复习了下在操作台上远程登录mysql的命令，主要是通过这个网址得知的https://blog.csdn.net/weixin_42394409/article/details/124399864

- sqlyog数据库修改问题

修改数据库中的数据在右下角显示数据已修改但没有保存，解决方式就是进行了修改之后点击左上角的保存即可

![](D:/Rolin的学习笔记/youdaonote-pull/youdaonote/youdaonote-images/WEBRESOURCE16e10b07adc443bb7ebc64b439a264a4.png)

- 控制台上没有正确删除共享域中的内容

产生这个问题是因为没有刷新，点一下别的再点回来就可以看到结果了

![](D:/Rolin的学习笔记/youdaonote-pull/youdaonote/youdaonote-images/WEBRESOURCE336a8424bf481e572e9981743fe7e40a.png)

- 配置全局异常处理器没有生效

配置了全局的异常处理器，但是测试的时候发现没有启动，问题原因是全局异常处理类的方法没有加上ExceptionHandler注解，加上就可以了

- 添加功能抛出500异常

报错信息如下2022-07-09 14:06:17.989 ERROR 5936 --- [nio-8080-exec-8] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.dao.DataIntegrityViolationException:

发生的异常是在我们进行公共字段自动填充的功能完善进行的测试时所发生的

问题产生的原因是我们没有给对应要填充的属性加入指定的TableField注解导致我们的公共字段没有进行填充，插入时的数据由于为空抛出异常导致的

- 已经有了公共处理异常类的情况下，前端仍然返回500异常

异常信息如下2022-07-09 16:09:23.105 ERROR 58928 --- [nio-8080-exec-5] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.dao.DuplicateKeyException:

这个异常信息说实话也看不出来什么，经过Debug我们发现问题发生在我们的统一异常处理类中的这行代码里，这里我们的对字符串进行分割，但是字符串压根没有2个，就会抛出数组下标越界异常，将这行代码删除，直接令该异常处理返回固定的提示信息就行了

```
if(ex.getMessage().contains("#23000")){
    String[] split = ex.getMessage().split(" ");
    String msg = split[2] + "已存在";
    return R.error("该名称已存在");
}
```

- 分类页面分页查询抛出异常

异常信息为2022-07-09 16:53:42.174 ERROR 57232 --- [nio-8080-exec-5] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.jdbc.BadSqlGrammarException:

产生这个异常的原因在于我们的实体类中多了一个字段，而数据库中没有这个字段，因此抛出了该异常，将实体类中数据库里不存在的字段删去即可

- 分类页面点击删除提示删除成功但数据库没有对应删除

产生这个问题的原因是，前端向后端发送数据是使用的变量名是ids而不是id，而我们后端写的代码里承接数据的变量名为id，这样id没有得到值，自然就无法删除，但仍然会执行后面的删除代码，因此会显示删除成功。

解决的方法是将后端的删除代码的变量名从id改为ids

- 项目无法正常启动

启动项目时报错，异常信息如下org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'commonController': Injection of autowired dependencies failed; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'reggie.path' in value "${reggie.path}"

其代表的意义是，我们对应的注解中获取reggie.path的值，但在对应的yml文件中没有该值，因此报错。产生这个错误的原因是我们在yml文件中指定对应的值的时候没有在:后加上一个空格再指定值导致的，把空格加上就能解决这个问题了

- 项目无法正常启动2

启动项目时报错，异常信息如下

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.

2022-07-12 16:28:45.095 ERROR 1608 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'requestMappingHandlerMapping' defined in class path resource [com/itheima/reggie/config/WebMvcConfig.class]: Invocation of init method failed; nested exception is java.lang.IllegalStateException: Ambiguous mapping. Cannot map 'dishController' method

com.itheima.reggie.controller.DishController#save(DishDto)

to {POST [/dish]}: There is already 'dishController' bean method

原因是我们我们所创建的方法注解里的PostMapping没有改成PutMapping，因此产生了方法上的创建冲突，改过来就没事了

